# Generated by Django 5.1.3 on 2024-11-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_code', models.CharField(max_length=45, unique=True)),
                ('department_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nusp', models.IntegerField(unique=True)),
                ('fullname', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('emailUSP', models.EmailField(max_length=45, unique=True)),
                ('hashed_password', models.CharField(max_length=126)),
                ('user_type', models.IntegerField()),
                ('user_photo', models.CharField(blank=True, max_length=256, null=True)),
                ('status_user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discipline_code', models.CharField(max_length=45, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('class_credits', models.IntegerField()),
                ('work_credits', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='reviews.department')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCoversSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_type', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='reviews.course')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='reviews.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.TextField()),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('status_comment', models.IntegerField()),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='reviews.comment')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.discipline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserCurtesComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reviews.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_comments', to='reviews.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserTakesCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='reviews.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='reviews.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserTookDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_completed', models.DateField()),
                ('note_teaching', models.IntegerField()),
                ('note_material', models.IntegerField()),
                ('note_difficulty', models.IntegerField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='reviews.discipline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines_taken', to='reviews.user')),
            ],
        ),
    ]
