# Generated by Django 5.1.3 on 2024-12-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='discipline_code',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.IntegerField(choices=[(2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], verbose_name='Ano de inicio'),
        ),
        migrations.AlterField(
            model_name='usertookdiscipline',
            name='semester_completed',
            field=models.IntegerField(choices=[(2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2024, '2024')], verbose_name='Ano em que fez a materia'),
        ),
    ]
