# Generated by Django 5.1.3 on 2024-11-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_user_user_type_alter_user_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
