# Generated by Django 5.1.3 on 2024-11-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_user_course_user_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(choices=[('ENG_AMBIENTAL', 'Engenharia Ambiental'), ('ENG_CIVIL', 'Engenharia Civil'), ('ENG_COMPUTACAO', 'Engenharia da Computação'), ('ENG_MINAS', 'Engenharia de Minas'), ('ENG_PETROLEO', 'Engenharia de Petróleo'), ('ENG_NAVAL', 'Engenharia Naval'), ('ENG_METALURGICA', 'Engenharia Metalúrgica'), ('ENG_PRODUCAO', 'Engenharia de Produção'), ('ENG_ELETRICA', 'Engenharia Elétrica'), ('ENG_MECANICA', 'Engenharia Mecânica'), ('ENG_MECATRONICA', 'Engenharia Mecatrônica'), ('ENG_QUIMICA', 'Engenharia Química'), ('ENG_MATERIAIS', 'Engenharia de Materiais')], default='ENG_MECATRONICA', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateField(),
        ),
    ]
