# Generated by Django 5.1.3 on 2024-11-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_user_course_alter_user_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='usertookdiscipline',
            name='semester_completed',
            field=models.PositiveSmallIntegerField(verbose_name='Ano em que fez a materia'),
        ),
    ]
